site_name: shapiq_attribution
site_author: MLOps_team
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true
            filters: ["!^_"]

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - API: api.md
  - Training: training.md
  - Monitoring: monitoring.md
  - Project structure: structure.md
  - Code reference: reference.md
